### ISSUE TITLE
link pages

### ISSUE THREAD

**Issue by JacobJax** [Room04/YelpCamp#16]
## Tasks
- [x] Create sign up page
- [x] Add necessary files
- [x] Link all pages together
- [x] Adjust for Logo
- [x] restyle `a` tags
